# -*- coding: utf-8 -*-
"""ai ml week 5 devsphere.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zlmjzMlO3-lP13c4gbrdvemmWGEZP12-
"""



"""# **Ai Task**"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


print("==============================================")
print("   DEVSPHERE - AI WEEK 5")
print("   AI-BASED INTELLIGENT SYSTEM")
print("==============================================")


# ==================================================
# 1. LOAD DATASET
# ==================================================

df = pd.read_csv("student_performance.csv")

print("\n========== ORIGINAL DATASET ==========")
print(df)


# ==================================================
# 2. DATA PREPROCESSING
# ==================================================

print("\n========== DATA PREPROCESSING ==========")

# Check missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing numerical values with mean
numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())

print("\nMissing values after preprocessing:")
print(df.isnull().sum())

print("\nData preprocessing completed successfully!")


# ==================================================
# 3. SELECT FEATURES AND TARGET
# ==================================================

X = df[["StudyHours", "Attendance", "PreviousScore"]]
y = df["Passed"]


# ==================================================
# 4. TRAIN / TEST SPLIT
# ==================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)


# ==================================================
# 5. FEATURE SCALING
# ==================================================

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


# ==================================================
# 6. TRAIN AI/ML MODEL
# ==================================================

model = LogisticRegression()

model.fit(X_train_scaled, y_train)

print("\n========== MODEL TRAINING ==========")
print("AI/ML model trained successfully!")


# ==================================================
# 7. ACCURACY EVALUATION
# ==================================================

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)

print("\n========== MODEL EVALUATION ==========")
print("Actual Values:   ", list(y_test))
print("Predicted Values:", list(y_pred))

print(f"\nModel Accuracy: {accuracy * 100:.2f}%")


# ==================================================
# 8. USER INPUT HANDLING
# ==================================================

print("\n==============================================")
print("       STUDENT PREDICTION SYSTEM")
print("==============================================")

print("\nEnter student information:")

study_hours = float(
    input("Study Hours: ")
)

attendance = float(
    input("Attendance Percentage: ")
)

previous_score = float(
    input("Previous Exam Score: ")
)


# ==================================================
# 9. CREATE USER INPUT DATA
# ==================================================

user_data = pd.DataFrame({
    "StudyHours": [study_hours],
    "Attendance": [attendance],
    "PreviousScore": [previous_score]
})


# Apply the same preprocessing/scaling
user_data_scaled = scaler.transform(user_data)


# ==================================================
# 10. MAKE PREDICTION
# ==================================================

prediction = model.predict(user_data_scaled)

prediction_probability = model.predict_proba(
    user_data_scaled
)

if prediction[0] == 1:
    result = "PASS"
else:
    result = "FAIL"


# ==================================================
# 11. DISPLAY RESULT
# ==================================================

print("\n==============================================")
print("             AI PREDICTION RESULT")
print("==============================================")

print(f"Study Hours: {study_hours}")
print(f"Attendance: {attendance}%")
print(f"Previous Score: {previous_score}")

print("\nPrediction:", result)

print(
    f"Pass Probability: "
    f"{prediction_probability[0][1] * 100:.2f}%"
)

print(
    f"Fail Probability: "
    f"{prediction_probability[0][0] * 100:.2f}%"
)


# ==================================================
# 12. RESULT VISUALIZATION
# ==================================================

print("\nGenerating result visualization...")

labels = ["Pass Probability", "Fail Probability"]

probabilities = [
    prediction_probability[0][1] * 100,
    prediction_probability[0][0] * 100
]

plt.figure(figsize=(8, 5))

bars = plt.bar(
    labels,
    probabilities
)

plt.title("AI Student Prediction Result")
plt.xlabel("Prediction")
plt.ylabel("Probability (%)")

plt.ylim(0, 100)

for bar, value in zip(bars, probabilities):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        value + 2,
        f"{value:.2f}%",
        ha="center"
    )

plt.tight_layout()

plt.show()


# ==================================================
# FINAL MESSAGE
# ==================================================

print("\n==============================================")
print("   AI-BASED INTELLIGENT SYSTEM COMPLETED")
print("==============================================")

"""## **ML Task**"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay
)


# ============================================================
# 1. PROGRAM HEADER
# ============================================================

print("=" * 60)
print("        DEVSPHERE - MACHINE LEARNING WEEK 5")
print("        MODEL EVALUATION + TUNING")
print("=" * 60)


# ============================================================
# 2. LOAD DATASET
# ============================================================

print("\n" + "=" * 60)
print("                    DATASET")
print("=" * 60)

df = pd.read_csv("student_classification_week5.csv")

print("\nDataset loaded successfully!")

print("\nDataset:")
print(df)

print("\nDataset Information:")
print(df.info())

print("\nDataset Shape:")
print(df.shape)


# ============================================================
# 3. DATA PREPROCESSING
# ============================================================

print("\n" + "=" * 60)
print("                DATA PREPROCESSING")
print("=" * 60)

print("\nMissing Values:")
print(df.isnull().sum())

# Fill missing numerical values if any
numeric_columns = df.select_dtypes(include="number").columns

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].mean())

# Remove duplicate rows
df = df.drop_duplicates()

print("\nMissing Values After Preprocessing:")
print(df.isnull().sum())

print("\nData preprocessing completed successfully!")


# ============================================================
# 4. DEFINE FEATURES AND TARGET
# ============================================================

X = df[[
    "StudyHours",
    "Attendance"
]]

y = df["Passed"]

print("\n" + "=" * 60)
print("             FEATURES AND TARGET")
print("=" * 60)

print("\nFeatures:")
print(X)

print("\nTarget:")
print(y)


# ============================================================
# 5. TRAIN-TEST SPLIT
# ============================================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("\n" + "=" * 60)
print("                TRAIN TEST SPLIT")
print("=" * 60)

print("\nTraining samples:", len(X_train))
print("Testing samples:", len(X_test))


# ============================================================
# 6. TRAIN MULTIPLE MACHINE LEARNING MODELS
# ============================================================

print("\n" + "=" * 60)
print("             TRAINING MULTIPLE MODELS")
print("=" * 60)


# -------------------------
# Logistic Regression
# -------------------------

logistic_model = LogisticRegression(
    random_state=42
)

logistic_model.fit(
    X_train,
    y_train
)

logistic_predictions = logistic_model.predict(
    X_test
)


# -------------------------
# Decision Tree
# -------------------------

decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

decision_tree_model.fit(
    X_train,
    y_train
)

decision_tree_predictions = decision_tree_model.predict(
    X_test
)


# -------------------------
# Random Forest
# -------------------------

random_forest_model = RandomForestClassifier(
    random_state=42
)

random_forest_model.fit(
    X_train,
    y_train
)

random_forest_predictions = random_forest_model.predict(
    X_test
)


print("\nAll three models trained successfully!")


# ============================================================
# 7. EVALUATION FUNCTION
# ============================================================

def evaluate_model(
    model_name,
    y_true,
    y_pred
):

    accuracy = accuracy_score(
        y_true,
        y_pred
    )

    precision = precision_score(
        y_true,
        y_pred,
        zero_division=0
    )

    recall = recall_score(
        y_true,
        y_pred,
        zero_division=0
    )

    f1 = f1_score(
        y_true,
        y_pred,
        zero_division=0
    )

    print("\n" + "-" * 60)
    print(model_name)
    print("-" * 60)

    print(
        f"Accuracy : {accuracy * 100:.2f}%"
    )

    print(
        f"Precision: {precision * 100:.2f}%"
    )

    print(
        f"Recall   : {recall * 100:.2f}%"
    )

    print(
        f"F1 Score : {f1 * 100:.2f}%"
    )

    return {
        "Model": model_name,
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1
    }


# ============================================================
# 8. EVALUATE ALL MODELS
# ============================================================

print("\n" + "=" * 60)
print("                MODEL EVALUATION")
print("=" * 60)

results = []

results.append(
    evaluate_model(
        "Logistic Regression",
        y_test,
        logistic_predictions
    )
)

results.append(
    evaluate_model(
        "Decision Tree",
        y_test,
        decision_tree_predictions
    )
)

results.append(
    evaluate_model(
        "Random Forest",
        y_test,
        random_forest_predictions
    )
)


# ============================================================
# 9. MODEL COMPARISON TABLE
# ============================================================

results_df = pd.DataFrame(results)

print("\n" + "=" * 60)
print("              MODEL COMPARISON")
print("=" * 60)

print("\n")
print(results_df.to_string(index=False))


# ============================================================
# 10. MODEL COMPARISON CHART
# ============================================================

print("\nGenerating model comparison chart...")

metrics = [
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score"
]

x = range(len(results_df["Model"]))

plt.figure(figsize=(10, 6))

width = 0.2

for i, metric in enumerate(metrics):

    values = results_df[metric]

    positions = [
        position + (i - 1.5) * width
        for position in x
    ]

    plt.bar(
        positions,
        values,
        width=width,
        label=metric
    )

plt.xticks(
    list(x),
    results_df["Model"]
)

plt.ylabel("Score")

plt.xlabel("Machine Learning Model")

plt.title(
    "Machine Learning Model Performance Comparison"
)

plt.ylim(
    0,
    1.1
)

plt.legend()

plt.tight_layout()

plt.show()


# ============================================================
# 11. HYPERPARAMETER TUNING
# ============================================================

print("\n" + "=" * 60)
print("                 MODEL TUNING")
print("=" * 60)

print("\nTuning Random Forest model...")


param_grid = {

    "n_estimators": [
        50,
        100,
        150
    ],

    "max_depth": [
        None,
        2,
        3,
        5
    ],

    "min_samples_split": [
        2,
        3,
        4
    ]
}


grid_search = GridSearchCV(

    estimator=RandomForestClassifier(
        random_state=42
    ),

    param_grid=param_grid,

    cv=2,

    scoring="accuracy",

    n_jobs=-1
)


grid_search.fit(
    X_train,
    y_train
)


# IMPORTANT:
# Correct sklearn attributes use ONE underscore at the end.

print("\nBest Parameters:")

print(
    grid_search.best_params_
)


print(
    f"\nBest Cross-Validation Accuracy: "
    f"{grid_search.best_score_ * 100:.2f}%"
)


# ============================================================
# 12. GET OPTIMIZED MODEL
# ============================================================

optimized_model = grid_search.best_estimator_

print("\nOptimized Random Forest model obtained successfully!")


# ============================================================
# 13. EVALUATE OPTIMIZED MODEL
# ============================================================

optimized_predictions = optimized_model.predict(
    X_test
)


optimized_accuracy = accuracy_score(
    y_test,
    optimized_predictions
)

optimized_precision = precision_score(
    y_test,
    optimized_predictions,
    zero_division=0
)

optimized_recall = recall_score(
    y_test,
    optimized_predictions,
    zero_division=0
)

optimized_f1 = f1_score(
    y_test,
    optimized_predictions,
    zero_division=0
)


print("\n" + "=" * 60)
print("             OPTIMIZED MODEL RESULTS")
print("=" * 60)

print(
    f"\nAccuracy : {optimized_accuracy * 100:.2f}%"
)

print(
    f"Precision: {optimized_precision * 100:.2f}%"
)

print(
    f"Recall   : {optimized_recall * 100:.2f}%"
)

print(
    f"F1 Score : {optimized_f1 * 100:.2f}%"
)


# ============================================================
# 14. CLASSIFICATION REPORT
# ============================================================

print("\n" + "=" * 60)
print("             CLASSIFICATION REPORT")
print("=" * 60)

print(
    classification_report(
        y_test,
        optimized_predictions,
        zero_division=0
    )
)


# ============================================================
# 15. CONFUSION MATRIX
# ============================================================

print("\nGenerating confusion matrix...")

cm = confusion_matrix(
    y_test,
    optimized_predictions
)

print("\nConfusion Matrix:")
print(cm)


disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Fail", "Pass"]
)

disp.plot()

plt.title(
    "Optimized Random Forest - Confusion Matrix"
)

plt.tight_layout()

plt.show()


# ============================================================
# 16. OPTIMIZED MODEL METRICS CHART
# ============================================================

print("\nGenerating optimized model metrics chart...")

optimized_metrics = {

    "Accuracy":
        optimized_accuracy,

    "Precision":
        optimized_precision,

    "Recall":
        optimized_recall,

    "F1 Score":
        optimized_f1
}


plt.figure(
    figsize=(8, 5)
)

plt.bar(
    optimized_metrics.keys(),
    optimized_metrics.values()
)

plt.title(
    "Optimized Random Forest Performance"
)

plt.xlabel(
    "Evaluation Metric"
)

plt.ylabel(
    "Score"
)

plt.ylim(
    0,
    1.1
)

plt.tight_layout()

plt.show()


# ============================================================
# 17. FINAL OUTPUT
# ============================================================

print("\n" + "=" * 60)
print("                 FINAL RESULT")
print("=" * 60)

print("\nModels trained:")
print("1. Logistic Regression")
print("2. Decision Tree")
print("3. Random Forest")

print("\nEvaluation metrics used:")
print("1. Accuracy")
print("2. Precision")
print("3. Recall")
print("4. F1 Score")

print("\nModel tuning:")
print("Random Forest hyperparameters optimized using GridSearchCV.")

print(
    f"\nBest Cross-Validation Accuracy: "
    f"{grid_search.best_score_ * 100:.2f}%"
)

print(
    f"Optimized Test Accuracy: "
    f"{optimized_accuracy * 100:.2f}%"
)

print("\n" + "=" * 60)
print("      ML WEEK 5 TASK COMPLETED SUCCESSFULLY")
print("=" * 60)